#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 SQLite Cloud, Inc.
"""
gen_unicode.py — src/unicode_classes.h, the general categories the
pre-tokenizers need, as sorted range tables.

`src/tokenizer.c` codes the pre-tokenization patterns directly rather than
carrying a regex engine, so it needs `\\p{L}`, `\\p{M}`, `\\p{N}`, `\\p{P}` and
`\\p{S}` as predicates. Until DeepSeek-V4.1 those were hand-written ranges
covering the scripts the two Kimi releases and GLM were exercised on, and
the gap was invisible because cl100k's pattern has only two classes and a
catch-all: a letter the table did not know fell into `[^\\s\\p{L}\\p{N}]+`,
which still produced a piece.

DeepSeek's pattern has five classes and no catch-all, so the gap became
visible immediately — a fullwidth `Ｃ` that is not in `\\p{L}` becomes `\\p{S}`
instead, joins the punctuation run beside it, and shifts every id after it.
tools/tokdiff.py --wide measured it on the two releases that were already
supported, on 24021 strings: Kimi-Linear 22937 identical before and 24017
after, GLM-5.3-Flash 22914 before and 24020 after. The twenty-one curated
strings in that file scored 21/21 both times, which is the other half of
the lesson.

The remainder in both is codepoints assigned after this file's Unicode
revision — `regex` and Oniguruma know them and the table does not — so
regenerating on a newer CPython moves the number. 15.0 to 16.0 was worth
three strings on Kimi-Linear and two on GLM.

Generated from the CPython `unicodedata` of whoever runs it, which is a
different Unicode revision from the Rust `regex` tables the releases
tokenize with. The version is written into the header so a disagreement
found later has somewhere to start. Regenerate with:

  python3 tools/gen_unicode.py > src/unicode_classes.h

and re-run `tools/tokdiff.py` for every container before committing the
result — this file changes how every prompt is split.
"""

import sys
import unicodedata

MAX = 0x110000
CLASSES = [
    ("L", "letters — \\p{L}"),
    ("M", "combining marks — \\p{M}"),
    ("N", "numbers — \\p{N}, every script's digits and the numeric symbols"),
    ("P", "punctuation — \\p{P}"),
    ("S", "symbols — \\p{S}, currency and math included"),
]


def ranges(prefix):
    out, start = [], None
    for cp in range(MAX):
        if unicodedata.category(chr(cp)).startswith(prefix):
            if start is None:
                start = cp
        elif start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, MAX - 1))
    return out


def main():
    w = sys.stdout.write
    w("/* SPDX-License-Identifier: Apache-2.0\n"
      " * Copyright 2026 SQLite Cloud, Inc.\n"
      " */\n"
      "/* unicode_classes.h — GENERATED by tools/gen_unicode.py. Do not edit.\n"
      f" *\n * Unicode {unicodedata.unidata_version}, via CPython's unicodedata.\n"
      " *\n"
      " * Sorted, non-overlapping [lo, hi] ranges per general category, for the\n"
      " * pre-tokenizers in tokenizer.c. Binary search, so the cost is ~10\n"
      " * comparisons per character and the whole table is a few KB of rodata —\n"
      " * which is the trade this file exists to make. The alternative was a\n"
      " * hand-written approximation, and its failure mode is not a wrong\n"
      " * answer but a differently-split prompt that nothing reports.\n"
      " */\n"
      "#ifndef WASTE_UNICODE_CLASSES_H\n"
      "#define WASTE_UNICODE_CLASSES_H\n"
      "\n#include <stdint.h>\n\n"
      "typedef struct { uint32_t lo, hi; } uc_range;\n")
    for name, desc in CLASSES:
        r = ranges(name)
        w(f"\n/* {desc}: {len(r)} ranges */\n"
          f"static const uc_range uc_{name.lower()}[] = {{\n")
        for i in range(0, len(r), 4):
            w("    " + " ".join(f"{{0x{a:04X},0x{b:04X}}},"
                                for a, b in r[i:i + 4]) + "\n")
        w("};\n")
    w("""
static int uc_in(const uc_range *t, int n, int c)
{
    if (c < 0) return 0;
    int lo = 0, hi = n - 1;
    while (lo <= hi) {
        const int mid = lo + (hi - lo) / 2;
        if ((uint32_t)c < t[mid].lo)      hi = mid - 1;
        else if ((uint32_t)c > t[mid].hi) lo = mid + 1;
        else                              return 1;
    }
    return 0;
}

#define UC_N(t) ((int)(sizeof(t) / sizeof(*(t))))
static int uc_is_letter(int c) { return uc_in(uc_l, UC_N(uc_l), c); }
static int uc_is_mark(int c)   { return uc_in(uc_m, UC_N(uc_m), c); }
static int uc_is_number(int c) { return uc_in(uc_n, UC_N(uc_n), c); }
static int uc_is_punct(int c)  { return uc_in(uc_p, UC_N(uc_p), c); }
static int uc_is_symbol(int c) { return uc_in(uc_s, UC_N(uc_s), c); }

#endif /* WASTE_UNICODE_CLASSES_H */
""")
    return 0


if __name__ == "__main__":
    sys.exit(main())
